/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 batmobile.glb 
Author: mohamedhussien (https://sketchfab.com/mohamedhussien)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/batmobil-car-aec9e037fc1c461b9293ede852ac3060
Title: Batmobil car
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function BatMobile(props) {
  const { nodes, materials } = useGLTF('/batmobile.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.025}>
        <group position={[-8.805, 58.988, 56.465]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <group position={[0.11, 0, -0.055]}>
            <mesh geometry={nodes.Tumbler_Main_Body_body__0.geometry} material={materials.body} />
            <mesh geometry={nodes.Tumbler_Main_Body_00_erged_0.geometry} material={materials['00_erged']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/batmobile.glb')
