/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model/scene.gltf --transform 
Files: model/scene.gltf [211.28KB] > /Users/lukecleland/dev/americanparallel/r3f/deloreon/scene-transformed.glb [5.28MB] (-2399%)
Author: Cristianolop (https://sketchfab.com/Cristianolop)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/delorean-highpoly-18ecd0636aaa4373a903b76f9050c291
Title: Delorean (highpoly)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Delorean(props) {
  const { nodes, materials } = useGLTF('./delorean.glb')

  // materials.PaletteMaterial001.metalness = 1;
  // materials.PaletteMaterial001.roughness = 0.3;

  return (
    <group {...props} dispose={null} castShadow>
      <mesh castShadow geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[1.985, 0.151, -1.784]} rotation={[-1.765, 1.492, -1.542]} scale={[0.079, 0.041, 0.088]} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.PaletteMaterial002} position={[0, 0, 4.13]} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.RearLight} position={[0, 0, 3.641]} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.RearLightOrange} position={[0, 0, 4.13]} />
      <mesh geometry={nodes.Object_51.geometry} material={materials.RearLightRed} position={[0, 0, 4.13]} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.RearLightWhite} position={[0, 0, 4.13]} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.LightSide2} position={[0, 0, 4.13]} />
      <mesh geometry={nodes.Object_61.geometry} material={materials.SideLight} position={[0.076, -0.043, -4.519]} />
      <mesh geometry={nodes.Object_186.geometry} material={materials.Tyres} position={[1.936, -0.881, -3.035]} scale={[0.974, 0.817, 0.817]} />
      <mesh geometry={nodes.Object_188.geometry} material={materials.Vidro} position={[0, 0, 4.13]} />
      <mesh geometry={nodes.Object_190.geometry} material={materials.Placa} position={[0, 0, 4.318]} />
      <mesh geometry={nodes.Object_192.geometry} material={materials['Material.002']} position={[1.865, -0.967, 3.06]} rotation={[0, 0.296, 0]} scale={[0.883, 0.741, 0.741]} />
    </group>
  )
}

useGLTF.preload('./delorean.glb')
