/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 lightning.glb 
Author: ChoochooLi (https://sketchfab.com/ChoochooLi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lightning-mcqueen-cars-3-driven-to-win-d7ef24d8cd40426787eee88fa7224fa0
Title: Lightning McQueen Cars 3 Driven To Win
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Lightning(props) {
  const { nodes, materials } = useGLTF('./lightning.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Eyes} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Object} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Object_1} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Object_2} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Object_3} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Object_5} />
      </group>
    </group>
  )
}

useGLTF.preload('./lightning.glb')
