/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mini.glb 
Author: Daniel Zhabotinsky (https://sketchfab.com/DanielZhabotinsky)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/british-compact-car-low-poly-model-f1e9c43c61bb492a9b15d84f9a16c0f7
Title: British compact car - Low poly model
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Mini(props) {
  const { nodes, materials } = useGLTF('./mini.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[56.679, 12.434, 0.076]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.bumper_rear_ASTNMINI_CHROME_0.geometry} material={materials.ASTNMINI_CHROME} position={[14.547, 0.335, -2.608]} />
      </group>
      <group position={[-43.575, 34.169, 0.064]}>
        <mesh geometry={nodes.sidemirrors_ASTNMINI_CHROME_0.geometry} material={materials.ASTNMINI_CHROME} position={[2.407, -24.29, 25.789]} />
      </group>
      <group position={[-41.369, 9.939, 24.434]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.313, 0.313, 0.276]}>
          <mesh geometry={nodes.tier_ASTNMINI_tier_1t_0.geometry} material={materials.ASTNMINI_tier_1t} position={[0.034, 0.152, 12.535]} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.313, 0.313, 0.276]}>
          <mesh geometry={nodes.rim_ASTNMINI_RIMCOLOUR_0.geometry} material={materials.ASTNMINI_RIMCOLOUR} position={[0.034, 0.152, 12.535]} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.313, 0.313, 0.276]}>
          <mesh geometry={nodes.rim_chrome_ASTNMINI_CHROME_0.geometry} material={materials.ASTNMINI_CHROME} position={[0.034, 0.152, 12.535]} />
        </group>
      </group>
      <group position={[-57.308, 10.858, 0.076]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0.057, 0, 1.576]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.bumper_front_ASTNMINI_CHROME_0.geometry} material={materials.ASTNMINI_CHROME} position={[14.547, 0.335, 2.608]} />
        </group>
        <group position={[0.057, 0, 1.576]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.numberplate_front_ASTNMINI_PLASTIC_0.geometry} material={materials.ASTNMINI_PLASTIC} position={[14.547, 0.335, 2.608]} />
        </group>
      </group>
      <group position={[56.261, 20.573, 0.064]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.backlights_trim_ASTNMINI_CHROME_0.geometry} material={materials.ASTNMINI_CHROME} position={[-97.429, -10.694, 25.789]} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.backlights_glass_ASTNMINI_headlights_ucb_0.geometry} material={materials.ASTNMINI_headlights_ucb} position={[-97.429, -10.694, 25.789]} />
        </group>
      </group>
      <group position={[-55.946, 18.314, 0.064]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.grill_void_ASTNMINI_VOID_0.geometry} material={materials.ASTNMINI_VOID} position={[14.778, -8.435, 25.789]} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.grill_ASTNMINI_CHROME_0.geometry} material={materials.ASTNMINI_CHROME} position={[14.778, -8.435, 25.789]} />
        </group>
      </group>
      <group position={[-0.881, 13.4, 0.064]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, 1.004]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.bottom_ASTNMINI_VOID_0.geometry} material={materials.ASTNMINI_VOID} position={[-40.287, -4.525, 25.789]} />
        </group>
        <group position={[-40.553, 0.103, -3.465]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 1.041]}>
          <mesh geometry={nodes.suspension_front_ASTNMINI_VOID_0.geometry} material={materials.ASTNMINI_VOID} position={[0.178, -0.111, 27.923]} />
        </group>
        <group position={[40.723, 0.103, -3.465]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 1.041]}>
          <mesh geometry={nodes.suspension_rear_ASTNMINI_VOID_0.geometry} material={materials.ASTNMINI_VOID} position={[0.178, -0.111, 27.923]} />
        </group>
      </group>
      <group position={[0.618, 30.165, 0.064]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[10.943, 0, 8.646]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.interior_ASTNMINI_VOID_0.geometry} material={materials.ASTNMINI_VOID} position={[-52.729, -28.933, 25.789]} />
        </group>
        <group position={[10.943, 0, 10.118]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.glass_ASTNMINI_GLASS_0.geometry} material={materials.ASTNMINI_GLASS} position={[-52.729, -30.404, 25.789]} />
        </group>
        <group position={[10.903, 0, 20.074]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.roof_ASTNMINI_ROOFCOLOUR_0.geometry} material={materials.ASTNMINI_ROOFCOLOUR} position={[-52.689, -40.36, 25.789]} />
        </group>
        <group position={[0.132, 0, -2.03]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.bodyshell_ASTNMINI_BODY_0.geometry} material={materials.ASTNMINI_BODY} position={[-41.918, -18.256, 25.789]} />
        </group>
        <group position={[0.132, 0, -2.03]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.bodyshell_chrometrim_ASTNMINI_CHROME_0.geometry} material={materials.ASTNMINI_CHROME} position={[-41.918, -18.256, 25.789]} />
        </group>
        <group position={[-57.297, 0, -13.914]}>
          <group position={[57.43, 0, 11.884]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.turnsignals_trim_ASTNMINI_CHROME_0.geometry} material={materials.ASTNMINI_CHROME} position={[-41.918, -18.256, 25.789]} />
          </group>
          <group position={[57.43, 0, 11.884]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.turnsighal_glass_ASTNMINI_headlights_ucb_0.geometry} material={materials.ASTNMINI_headlights_ucb} position={[-41.918, -18.256, 25.789]} />
          </group>
        </group>
        <group position={[-57.852, -19.339, -5.58]}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={[0.591, 1, 1]}>
            <mesh geometry={nodes.headlights_glass_ASTNMINI_GLASS_0.geometry} material={materials.ASTNMINI_GLASS} position={[16.559, -14.706, 6.45]} />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={[0.591, 1, 1]}>
            <mesh geometry={nodes.headlights_reflector_ASTNMINI_headlights_ucb_0.geometry} material={materials.ASTNMINI_headlights_ucb} position={[16.559, -14.706, 6.45]} />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={[0.591, 1, 1]}>
            <mesh geometry={nodes.headlights_ASTNMINI_CHROME_0.geometry} material={materials.ASTNMINI_CHROME} position={[16.559, -14.706, 6.45]} />
          </group>
        </group>
        <mesh geometry={nodes.rear_numperplate_ASTNMINI_PLASTIC_0.geometry} material={materials.ASTNMINI_PLASTIC} position={[58.102, -0.052, -10.205]} rotation={[0, 1.396, 1.571]} scale={[1, 1, 1.638]} />
      </group>
      <group position={[39.668, 9.939, 24.434]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.313, 0.313, 0.276]}>
          <mesh geometry={nodes.tier001_ASTNMINI_tier_1t_0.geometry} material={materials.ASTNMINI_tier_1t} position={[0.034, 0.152, 12.535]} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.313, 0.313, 0.276]}>
          <mesh geometry={nodes.rim001_ASTNMINI_RIMCOLOUR_0.geometry} material={materials.ASTNMINI_RIMCOLOUR} position={[0.034, 0.152, 12.535]} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.313, 0.313, 0.276]}>
          <mesh geometry={nodes.rim_chrome001_ASTNMINI_CHROME_0.geometry} material={materials.ASTNMINI_CHROME} position={[0.034, 0.152, 12.535]} />
        </group>
      </group>
      <group position={[39.668, 9.939, -24.292]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.313, 0.313, 0.276]}>
          <mesh geometry={nodes.rim002_ASTNMINI_RIMCOLOUR_0.geometry} material={materials.ASTNMINI_RIMCOLOUR} position={[0.034, 0.152, 12.535]} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.313, 0.313, 0.276]}>
          <mesh geometry={nodes.tier002_ASTNMINI_tier_1t_0.geometry} material={materials.ASTNMINI_tier_1t} position={[0.034, 0.152, 12.535]} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.313, 0.313, 0.276]}>
          <mesh geometry={nodes.rim_chrome002_ASTNMINI_CHROME_0.geometry} material={materials.ASTNMINI_CHROME} position={[0.034, 0.152, 12.535]} />
        </group>
      </group>
      <group position={[-41.369, 9.939, -24.292]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.313, 0.313, 0.276]}>
          <mesh geometry={nodes.tier003_ASTNMINI_tier_1t_0.geometry} material={materials.ASTNMINI_tier_1t} position={[0.034, 0.152, 12.535]} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.313, 0.313, 0.276]}>
          <mesh geometry={nodes.rim003_ASTNMINI_RIMCOLOUR_0.geometry} material={materials.ASTNMINI_RIMCOLOUR} position={[0.034, 0.152, 12.535]} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.313, 0.313, 0.276]}>
          <mesh geometry={nodes.rim_chrome003_ASTNMINI_CHROME_0.geometry} material={materials.ASTNMINI_CHROME} position={[0.034, 0.152, 12.535]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./mini.glb')
